package com.lrr.eduService.bean;

import com.lrr.eduService.bean.base.BaseCrmBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBanner extends BaseCrmBanner<CrmBanner> {
	
}

