package com.lrr.eduService.bean;

import com.lrr.eduService.bean.base.BaseEduChapter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EduChapter extends com.lrr.eduService.bean.base.BaseEduChapter<EduChapter> {
	
}

