package com.lrr.eduService.bean;

import com.lrr.eduService.bean.base.BaseEduCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EduCourse extends BaseEduCourse<EduCourse> {
	
}

