package com.lrr.eduService.bean;

import com.lrr.eduService.bean.base.BaseEduCollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EduCollect extends BaseEduCollect<EduCollect> {
	
}

