package com.lrr.eduService.bean;

import com.lrr.eduService.bean.base.BaseEduSubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EduSubject extends BaseEduSubject<EduSubject> {
	
}

