package com.lrr.eduService.bean;

import com.lrr.eduService.bean.base.BaseEduTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EduTeacher extends BaseEduTeacher<EduTeacher> {
	
}

