package com.lrr.eduService.bean;

import com.lrr.eduService.bean.base.BaseEduVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EduVideo extends BaseEduVideo<EduVideo> {
	
}

