package com.lrr.eduService.bean;

import com.lrr.eduService.bean.base.BasePlcMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlcMember extends BasePlcMember<PlcMember> {
	
}

