package com.lrr.eduService.bean;

import com.lrr.eduService.bean.base.BaseTPayLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TPayLog extends BaseTPayLog<TPayLog> {
	
}

