package com.lrr.eduService.bean;

import com.lrr.eduService.bean.base.BaseUcenterMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UcenterMember extends BaseUcenterMember<UcenterMember> {
	
}

