package com.lrr.eduService.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEduCourse<M extends BaseEduCourse<M>> extends Model<M> implements IBean {

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 课程ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 课程ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 课程讲师ID
	 */
	public void setTeacherId(java.lang.String teacherId) {
		set("teacherId", teacherId);
	}
	
	/**
	 * 课程讲师ID
	 */
	public java.lang.String getTeacherId() {
		return getStr("teacherId");
	}
	
	/**
	 * 课程专业ID
	 */
	public void setSubjectId(java.lang.String subjectId) {
		set("subjectId", subjectId);
	}
	
	/**
	 * 课程专业ID
	 */
	public java.lang.String getSubjectId() {
		return getStr("subjectId");
	}
	
	/**
	 * 课程专业父级ID
	 */
	public void setSubjectParentId(java.lang.String subjectParentId) {
		set("subjectParentId", subjectParentId);
	}
	
	/**
	 * 课程专业父级ID
	 */
	public java.lang.String getSubjectParentId() {
		return getStr("subjectParentId");
	}
	
	/**
	 * 课程标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 课程标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 课程销售价格，设置为0则可免费观看
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 课程销售价格，设置为0则可免费观看
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	/**
	 * 课程封面图片路径
	 */
	public void setCover(java.lang.String cover) {
		set("cover", cover);
	}
	
	/**
	 * 课程封面图片路径
	 */
	public java.lang.String getCover() {
		return getStr("cover");
	}
	
	/**
	 * 销售数量
	 */
	public void setBuyCount(java.math.BigInteger buyCount) {
		set("buyCount", buyCount);
	}
	
	/**
	 * 销售数量
	 */
	public java.math.BigInteger getBuyCount() {
		return get("buyCount");
	}
	
	/**
	 * 课程状态 Draft未发布  Normal已发布
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 课程状态 Draft未发布  Normal已发布
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
}

