package com.lrr.eduService.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEduVideo<M extends BaseEduVideo<M>> extends Model<M> implements IBean {

	/**
	 * 视频ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 视频ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 课程ID
	 */
	public void setCourseId(java.lang.String courseId) {
		set("courseId", courseId);
	}
	
	/**
	 * 课程ID
	 */
	public java.lang.String getCourseId() {
		return getStr("courseId");
	}
	
	/**
	 * 章节ID
	 */
	public void setChapterId(java.lang.String chapterId) {
		set("chapterId", chapterId);
	}
	
	/**
	 * 章节ID
	 */
	public java.lang.String getChapterId() {
		return getStr("chapterId");
	}
	
	/**
	 * 节点名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 节点名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 云端视频资源
	 */
	public void setVideoSourceId(java.lang.String videoSourceId) {
		set("videoSourceId", videoSourceId);
	}
	
	/**
	 * 云端视频资源
	 */
	public java.lang.String getVideoSourceId() {
		return getStr("videoSourceId");
	}
	
	/**
	 * 原始文件名称
	 */
	public void setVideoOriginalName(java.lang.String videoOriginalName) {
		set("videoOriginalName", videoOriginalName);
	}
	
	/**
	 * 原始文件名称
	 */
	public java.lang.String getVideoOriginalName() {
		return getStr("videoOriginalName");
	}
	
	/**
	 * 是否可以试听：0收费 1免费
	 */
	public void setIsFree(java.lang.Integer isFree) {
		set("isFree", isFree);
	}
	
	/**
	 * 是否可以试听：0收费 1免费
	 */
	public java.lang.Integer getIsFree() {
		return getInt("isFree");
	}
	
	/**
	 * Empty未上传 Transcoding转码中  Normal正常
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * Empty未上传 Transcoding转码中  Normal正常
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 优先级显示
	 */
	public void setPrio(java.lang.Integer prio) {
		set("prio", prio);
	}
	
	/**
	 * 优先级显示
	 */
	public java.lang.Integer getPrio() {
		return getInt("prio");
	}
	
}

