package com.lrr.eduService.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUcenterMember<M extends BaseUcenterMember<M>> extends Model<M> implements IBean {

	/**
	 * 会员id
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 会员id
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 微信openid
	 */
	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}
	
	/**
	 * 微信openid
	 */
	public java.lang.String getOpenid() {
		return getStr("openid");
	}
	
	/**
	 * 手机号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 昵称，账户名
	 */
	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}
	
	/**
	 * 昵称，账户名
	 */
	public java.lang.String getNickname() {
		return getStr("nickname");
	}
	
	/**
	 * 用户头像
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 用户头像
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
	/**
	 * 性别
	 */
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	/**
	 * 性别
	 */
	public java.lang.String getSex() {
		return getStr("sex");
	}
	
}

