package com.lrr.eduService.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTPayLog<M extends BaseTPayLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}
	
	/**
	 * 订单号
	 */
	public java.lang.String getOrderNo() {
		return getStr("orderNo");
	}
	
	/**
	 * 支付完成时间
	 */
	public void setPayTime(java.util.Date payTime) {
		set("payTime", payTime);
	}
	
	/**
	 * 支付完成时间
	 */
	public java.util.Date getPayTime() {
		return getDate("payTime");
	}
	
	/**
	 * 支付金额（分）
	 */
	public void setTotalFee(java.math.BigDecimal totalFee) {
		set("totalFee", totalFee);
	}
	
	/**
	 * 支付金额（分）
	 */
	public java.math.BigDecimal getTotalFee() {
		return get("totalFee");
	}
	
	/**
	 * 交易状态
	 */
	public void setTradeState(java.lang.String tradeState) {
		set("tradeState", tradeState);
	}
	
	/**
	 * 交易状态
	 */
	public java.lang.String getTradeState() {
		return getStr("tradeState");
	}
	
}

