package com.lrr.eduService.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlcMember<M extends BasePlcMember<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 账号
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * 账号
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 后台管理员权限
	 */
	public void setAuto(java.lang.Integer auto) {
		set("auto", auto);
	}
	
	/**
	 * 后台管理员权限
	 */
	public java.lang.Integer getAuto() {
		return getInt("auto");
	}
	
	/**
	 * 头像
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 头像
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
}

