package com.lrr.eduService.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEduSubject<M extends BaseEduSubject<M>> extends Model<M> implements IBean {

	/**
	 * 课程类别ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 课程类别ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 类别名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 类别名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 父ID
	 */
	public void setParentId(java.lang.String parentId) {
		set("parentId", parentId);
	}
	
	/**
	 * 父ID
	 */
	public java.lang.String getParentId() {
		return getStr("parentId");
	}
	
}

