package com.lrr.eduService.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEduCollect<M extends BaseEduCollect<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 用户id
	 */
	public void setMemberId(java.lang.String memberId) {
		set("memberId", memberId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.String getMemberId() {
		return getStr("memberId");
	}
	
	/**
	 * 课程id
	 */
	public void setCourseId(java.lang.String courseId) {
		set("courseId", courseId);
	}
	
	/**
	 * 课程id
	 */
	public java.lang.String getCourseId() {
		return getStr("courseId");
	}
	
}

