package com.lrr.eduService.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmBanner<M extends BaseCrmBanner<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 图片地址
	 */
	public void setImageUrl(java.lang.String imageUrl) {
		set("imageUrl", imageUrl);
	}
	
	/**
	 * 图片地址
	 */
	public java.lang.String getImageUrl() {
		return getStr("imageUrl");
	}
	
	/**
	 * 链接地址
	 */
	public void setLinkUrl(java.lang.String linkUrl) {
		set("linkUrl", linkUrl);
	}
	
	/**
	 * 链接地址
	 */
	public java.lang.String getLinkUrl() {
		return getStr("linkUrl");
	}
	
}

