package com.lrr.eduService.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEduChapter<M extends BaseEduChapter<M>> extends Model<M> implements IBean {

	/**
	 * 章节ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 章节ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 课程ID
	 */
	public void setCourseId(java.lang.String courseId) {
		set("courseId", courseId);
	}
	
	/**
	 * 课程ID
	 */
	public java.lang.String getCourseId() {
		return getStr("courseId");
	}
	
	/**
	 * 章节名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 章节名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 章节优先级
	 */
	public void setPrio(java.lang.Integer prio) {
		set("prio", prio);
	}
	
	/**
	 * 章节优先级
	 */
	public java.lang.Integer getPrio() {
		return getInt("prio");
	}
	
}

