package com.lrr.eduService.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEduTeacher<M extends BaseEduTeacher<M>> extends Model<M> implements IBean {

	/**
	 * 讲师ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 讲师ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 讲师姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 讲师姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 讲师简介
	 */
	public void setIntro(java.lang.String intro) {
		set("intro", intro);
	}
	
	/**
	 * 讲师简介
	 */
	public java.lang.String getIntro() {
		return getStr("intro");
	}
	
	/**
	 * 讲师资历,一句话说明讲师
	 */
	public void setLevel(java.lang.String level) {
		set("level", level);
	}
	
	/**
	 * 讲师资历,一句话说明讲师
	 */
	public java.lang.String getLevel() {
		return getStr("level");
	}
	
	/**
	 * 讲师头像
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 讲师头像
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
}

